kind: SparkApplication
apiVersion: sparkoperator.k8s.io/v1beta2
metadata:
  name: pyspark-pi
spec:
  driver:
    coreLimit: 1200m
    cores: 1
    labels:
      version: 3.1.1
    memory: 512m
    serviceAccount: spark-service-account
    volumeMounts:
      - mountPath: /tmp
        name: test-volume
  executor:
    cores: 1
    instances: 1
    labels:
      version: 3.1.1
    memory: 512m
    volumeMounts:
      - mountPath: /tmp
        name: test-volume
  image: 'gcr.io/spark-operator/spark-py:v3.1.1'
  imagePullPolicy: Always
  mainApplicationFile: 'local:///opt/spark/examples/src/main/python/pi.py'
  arguments:
    - '1000'
  mode: cluster
  pythonVersion: '3'
  restartPolicy:
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
    type: OnFailure
  sparkVersion: 3.1.1
  type: Python
  volumes:
    - hostPath:
        path: /tmp
        type: Directory
      name: test-volume
